spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  mustache:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
  devtools:
    livereload:
      enabled: true

server:
  port: 19090
